### ISSUE TITLE
hash_req_body in vcl_recv

### ISSUE THREAD

**Issue by arteta22000** [aondio/libvmod-bodyaccess#11]
Hi,

Sorry for my english :) 
why can not we put hash_req_body in vcl_recv ? I try to recover the value of a post parameter to send with vmod curl:

Example:
set req.http.x.param1= bodyaccess.hash_req_body(param1); 
...
curl.get("http://example.com/test");
curl.set_method("PURGE");
curl.header_add("param: " + req.http.x.param1);

is there a solution to do that ?

Thanks !

**Comment by aondio** [comment]
HI @arteta22000, sorry for the late reply.
hash_req_body() returns nothing because it's only task is to add a value to the hash table which can't be user-exposed. The hash table can be modified only in vcl_hash.
