### ISSUE TITLE
Add function for parse body

### ISSUE THREAD

**Issue by arteta22000** [aondio/libvmod-bodyaccess#12]
Hi,

"**rematch_req_body**" is useful, but it would be practical to have a function that parses the body.

Example with old mod "libvmod-parsereq":

---

vcl_xxxx {
  set resp.http.hoge = parsereq.param(post, "hoge");
}

//return
hoge: hogevalue

---

Could you add this function ?

**Comment by aondio** [comment]
Hi @arteta22000, any reason why you closed this request?

**Comment by arteta22000** [comment]
Hi aondio,

manipulation error, sorry.
you think it is possible to add this feature ?

**Comment by aondio** [comment]
Hi, 
sorry for the late reply. I didn't have the time to check it it possible to implement such a request, I definitely agree it would be useful, but I'm still not sure if it can be done.

I'll get back to you with more info.

**Comment by aondio** [comment]
Hi,
at the moment there are no plans to add this function.
If you have a patch you'd like to submit I'll gladly review it.

I'll close this request.
Thanks for your involvement.
