### ISSUE TITLE
Error after ran 'make'

### ISSUE THREAD

**Issue by Rod-Gomes** [aondio/libvmod-bodyaccess#15]
I was installing this module when I received the error below:

```
 In file included from vmod_core.h:6:0,
                  from vmod_core.c:1:
 /usr/include/varnish/cache/cache.h:917:9: note: expected 'int (*)(struct req *, void *, void *, size_t)' but argument is of type 'int (*)(void *, int,  const void *, ssize_t)'
  ssize_t VRB_Iterate(struct req *req, req_body_iter_f *func, void *priv);
          ^
 cc1: all warnings being treated as errors
 make[2]: ** [vmod_core.lo] Error 1
 make[2]: Exiting directory '/root/libvmod-bodyaccess/src'
 make[1]: ** [all-recursive] Error 1
 make[1]: Exiting directory '/root/libvmod-bodyaccess'
 make: ** [all] Error 2
```

This happened when I ran `make`.
My Environment is: CentOS Linux release 7.2.1511 (Core)

**Comment by aondio** [comment]
Hi,
which varnish version is it? and which vmod branch are you compiling?

**Comment by Rod-Gomes** [comment]
Hello @aondio I tried to compile the latest version 86153d2.

````
# varnishd -V
varnishd (varnish-4.1.4 revision 4529ff7)
````

I just did git clone and ran:
```
./autogen.sh
./configure
make
```

Like you teach in the [installation](https://github.com/aondio/libvmod-bodyaccess#installation).

**Comment by aondio** [comment]
Hi @Rod-Gomes, branch 5.0 compiles only against Varnish Cache 5.0.
Furthermore this vmod actually behaves as expected only with Varnish 5.0; branches 4.0 and 4.1 are not maintained anymore due to this bug: https://github.com/varnishcache/varnish-cache/issues/1927 which is fix in Varnish 5.0, but won't be backported to previous versions.

**Comment by Rod-Gomes** [comment]
Hello @aondio, but this bug is not just for some cases?
What I want to do is pretty simple, I'd like to test to see if I'll be affected by the bug.

Do you think if I install a previous branch is okay or I should not really use with version 4.1?

I can not upgrade to 5.0 now because it's fresh. I get a lot of traffic and I can't risk getting offline. :/

Thank you!

**Comment by aondio** [comment]
Hi @Rod-Gomes,
can you please expand a bit on what you want to do? So I'll be able to give you my best advice on it.

FYI if you want to test it out you must compile the branch 4.1 against Varnish 4.1

**Comment by Rod-Gomes** [comment]
Hello @aondio ,

Basically what I want to do is this:

```
sub vcl_recv {
	if (req.url ~ "(?i)/admin-ajax\.php" && req.method == "POST") {
		set req.http.x-method = req.method;
		std.cache_req_body(512KB);
	}
	return(hash);
}

sub vcl_hash {
	if (req.url ~ "(?i)/admin-ajax\.php" && req.method == "POST") {
		bodyaccess.hash_req_body();
	}
	return (lookup);
}

sub vcl_backend_fetch {
	if (bereq.url ~ "(?i)/admin-ajax\.php" && bereq.http.x-method == "POST") {
		set bereq.method = "POST";
		set beresp.ttl = 5s;
		set beresp.grace = 1m;
	}
}
```
_I do not know if it works, not tested._

Cache `/admin-ajax.php` page for method `POST`

**Comment by aondio** [comment]
Hi @Rod-Gomes,
I would suggest you to test it, the worst that could happen is that it doesn't work.

**Comment by Rod-Gomes** [comment]
Hello @aondio,
The branch 4.1 compile works fine, however, I've done several tests, `cache_req_body` does not work at all. :(

I'll wait for the stable version of Varnish Cache 5.0.
Thanks for your help!
