### ISSUE TITLE
Something planned about response body access?

### ISSUE THREAD

**Issue by rodricels** [aondio/libvmod-bodyaccess#18]
First of all, thanks for this vmod; I think that this functionality should be in varnish-cache core.

Searching more information about this Vmod I found that the initial purpose was gain access to req and beresp body, but only the request body part was finished. 

https://www.varnish-cache.org/lists/pipermail/varnish-dev/2015-June/008338.html
https://www.varnish-cache.org/lists/pipermail/varnish-dev/2015-August/008472.html
https://www.varnish-cache.org/trac/wiki/VDD15Q3

This would open new possibilities, like:
- inject, remove data, fix backend errors (like malformed URL in emergency case)
- invalidate cache of request with errors declared in the body but 200 in the status code (like graphQL does)
- retry with another backend if the request contains a empty body
- etc...

It something planned about access to the response body?

**Comment by aondio** [comment]
Hi @rodricels, apologies for the very late response.
So far Varnish-Cache requires some architectural modifications to allow any VMOD to be able to modify anything that happens on the backend side. I agree it is a very interesting feature/vmod function to have, hence patches to fix this in Varnish-Cache are more than welcome ;)
