### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by aondio** [aondio/libvmod-bodyaccess#6]
Misleading documentation, buffer_req_something returns a boolean now.

**Comment by blindpet** [comment]
@aondio I mistyped the vcl you helped me make on IRC. This is no longer working:

```
if ((req.method == "POST" || req.method == "PUT") && !( req.http.cookie ~ "wordpress_logged_in" ) && !(req.url ~ "wp-login\.php")) {
set req.http.x-method = req.method;
std.cache_req_body(110B);
set req.http.x-len = bodyaccess.len_req_body();
return(hash);
}
```

I get this error

```
Expected an action, 'if', '{' or '}'
('input' Line 96 Pos 1)
std.cache_req_body(110B);
##################-------
```

I hope your memory is better than mine

**Comment by aondio** [comment]
Hi,
do you have "import std; " at the beginning of your VCL?

**Comment by blindpet** [comment]
Ah yes that was it! I am going to start a new issue for this new problem. I can't find you on irc atm.

```
-   FetchError     Request body too big to cache
-   Debug          "VRT_CacheReqBody(110): -1"
-   VCL_Error      Unbuffered req.body
-   ReqHeader      x-len: -1
```

Increasing std.cache_req_body(110KB); seems to have fixed that error

**Comment by aondio** [comment]
Hi, it means you req body is bigger than the value you used in std.cache_req_body(BYTES size), try to bump up the size param.
